# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        none

# Server
destination:      _gh_pages
host:             127.0.0.1
port:             3001
baseurl:          /GRNsight
encoding:         UTF-8
